rest_platform_homepage:
    path:     /
    defaults: { _controller: restPlatformBundle:Default:index }

articles:
    resource: "@restPlatformBundle/Controller/ArticleController.php"
    prefix:   /
    type:     annotation